CREATE TABLE TASKS(
    TASK_ID INTEGER NOT NULL,
    DATE_ADDED DATETIME DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION VARCHAR(255),
    STATUS VARCHAR(255),
    TITLE VARCHAR(255),
    TYPE VARCHAR(255),
    USER_USER_ID INTEGER
);
ALTER TABLE TASKS ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(TASK_ID);  

CREATE TABLE USERS(
    USER_ID INTEGER NOT NULL,
    EMAIL VARCHAR(255),
    LAST_NAME VARCHAR(255),
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    REGISTRATION_DATE_AND_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS BOOLEAN DEFAULT FALSE
);        
ALTER TABLE USERS ADD CONSTRAINT CONSTRAINT_4D PRIMARY KEY(USER_ID);   

ALTER TABLE TASKS ADD CONSTRAINT FKPMRSAIKUG4G2IA9G3NDHNMNF5 FOREIGN KEY(USER_USER_ID) REFERENCES USERS(USER_ID);
